pipeline

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,4 +1,5 @@
 name: Makefile CI
+
 permissions:
   contents: write
   actions: read
@@ -95,19 +96,17 @@ jobs:
 
     - name: Run Norminette
       run: |
-        echo "Norminette location:"
-        whereis norminette
-        echo "Norminette version:"
-        norminette -v || echo "Failed to get Norminette version"
         cd ~/work/printf/printf
-        echo "Current directory: $(pwd)"
-        ls -la
         norminette
-      shell: /usr/bin/bash -e {0}
+
+    - name: Compile Libft (if needed)
+      run: |
+        cd ~/work/printf/printf/libft
+        make clean && make
 
     - name: Set TERM environment variable
       run: echo "TERM=xterm" >> $GITHUB_ENV
-      
+
     - name: Run Francinette
       id: check_phrase
       run: |
@@ -120,26 +119,28 @@ jobs:
         echo "Norminette version:"
         norminette -v || echo "Failed to get Norminette version"
         echo "Ejecutando Francinette:"
-        script -e -c "stdbuf -oL ~/francinette/tester.sh | tee francinette_output.log" /dev/null
+        script -e -c "stdbuf -oL ~/francinette/tester.sh printf | tee francinette_output.log" /dev/null
         search_result=$(grep -rnil "All tests passed! Congratulations!" .)
         echo "Search result: $search_result"
-        if echo "$search_result" | grep -q "output.log"; then
+        if grep -q "All tests passed! Congratulations!" francinette_output.log; then
           echo "output.log found containing 'All tests passed! Congratulations!'."
           echo "FOUND_PHRASE=true" >> $GITHUB_ENV
         else
           echo "FOUND_PHRASE=false" >> $GITHUB_ENV
+          echo "Error details:"
+          grep "Error" francinette_output.log || echo "No specific errors found"
         fi
 
     - name: Create tarball of Francinette Export Tests
       run: |
         cd ~
-        tar -czf francinette_exp_tst.tar.gz francinette/temp/
+        tar -czf francinette_printf_tests.tar.gz francinette/temp/
 
     - name: Upload Francinette Export Tests artifact
       uses: actions/upload-artifact@v3
       with:
-        name: francinette-exp-test
-        path: ~/francinette_exp_tst.tar.gz
+        name: francinette-printf-tests
+        path: ~/francinette_printf_tests.tar.gz
         if-no-files-found: warn
 
     - name: Checkout repository
